name: college_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cloud_firestore: ^4.8.2
  file_picker: ^8.0.0+1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.4.0
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_custom_carousel_slider: ^1.2.0
  flutter_riverpod: ^2.3.6
  go_router: ^9.0.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  horizontal_calendar: ^1.1.2
  http: ^1.1.0
  intl: ^0.18.0
  ionicons: ^0.2.2
  page_transition: ^2.0.1-nullsafety.0
  path_provider: ^2.0.15
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  sizer: ^2.0.15
  stack_trace: ^1.11.0
  syncfusion_flutter_pdfviewer: ^23.1.42
  tuple: ^2.0.2
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.5
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/xie.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/tiles/
