name: college_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  page_transition: ^2.0.1-nullsafety.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
