name: college_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.1-nullsafety.0
  intl: ^0.18.0
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
